baseURL = "https://jacobbaek.github.io/"
languageCode = "ko-kr"
defaultContentLanguage = "en-us"
title = "Welcome to JacobBaek Page"
theme = "aether"

[permalinks]
    post = "/:year/:filename"

[taxonomies]
    tag = "tags"
    archive = "archives"

publishDir = "jacobbaek.github.io"
